## Basics of Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array((1,2,3,4))
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [3]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [4]:
c[1,2]

6

In [5]:
c[:0]

array([], shape=(0, 3), dtype=int32)

In [6]:
c[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
c[:1]

array([[1, 2, 3]])

In [8]:
c[1:]

array([[4, 5, 6]])

In [9]:
type(c)

numpy.ndarray

In [10]:
num = np.zeros((3,4))
print(num)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# 1 is staring node 30 is end node 5 is interval for which we wanna print result
r = np.arange(1,30,5)
r

array([ 1,  6, 11, 16, 21, 26])

In [12]:
x = np.linspace(1,2,3)
x

array([1. , 1.5, 2. ])

In [13]:
f = np.full((4,5),7)
print(f)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [14]:
# Generates 3,4 array in random numbers 
o = np.random.random((3,4))
o

array([[0.92973011, 0.16596761, 0.13866681, 0.0313142 ],
       [0.79347641, 0.61277759, 0.98970928, 0.44989099],
       [0.94921886, 0.52920537, 0.43707473, 0.16979418]])

In [15]:
q = np.array([[1,2,3,4],[5,6,7,8]])
print(q)
print(q.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [16]:
q.shape = (4,2)
print(q.shape[0])
print(q)

4
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
q

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
w = np.arange(10)
print(w)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
w.size

10

In [20]:
# Number of dimenstion in the array ...
q.ndim

2

In [21]:
q.dtype

dtype('int32')

In [22]:
v = np.linspace(1,8,10)
print(v)
print(v.dtype)

[1.         1.77777778 2.55555556 3.33333333 4.11111111 4.88888889
 5.66666667 6.44444444 7.22222222 8.        ]
float64


## Numpy Array Maths Operations

In [23]:
# Addition
a = np.array([1,6])
np.sum(a)

7

In [24]:
k = np.array([[1,6],[1,10]])
np.sum(k)

18

In [25]:
# Subtraction
u = ([1,6])
np.subtract(u,a)

array([0, 0])

In [26]:
r = np.array([[1,1],[1,1]])
o = np.array([[1,1],[1,1]])
np.subtract(r,o)

array([[0, 0],
       [0, 0]])

In [27]:
# Addition from various sources
np.sum([r,o],axis = 0)

array([[2, 2],
       [2, 2]])

In [28]:
# Matrix Multiplication
np.multiply(r,o)

array([[1, 1],
       [1, 1]])

In [29]:
q = np.array([[2,5],[5,3]])
p = np.array([[1,4],[2,7]])
print(np.multiply(q,p))

[[ 2 20]
 [10 21]]


In [30]:
# Matrix Division
np.divide(q,p)

array([[2.        , 1.25      ],
       [2.5       , 0.42857143]])

In [31]:
z = 12
np.sqrt(z)

3.4641016151377544

In [32]:
np.exp(z)

162754.79141900392

In [33]:
np.sin(z)

-0.5365729180004349

In [34]:
np.cos(z)

0.8438539587324921

In [35]:
np.log(z)

2.4849066497880004

In [36]:
# Equalfunc
x = [1,2,3]
u = [1,2,3]
np.equal(x,u)

array([ True,  True,  True])

In [37]:
np.array_equal(x,u)

True

## Aggregate Function

In [38]:
a = np.array([1,2,3,4])
np.min(a)

1

In [39]:
b = [1,2,3,4,5]
print(np.max(b))
print(np.min(b))

5
1


In [40]:
np.mean(b)

3.0

In [41]:
np.median(b)

3.0

In [42]:
np.std(b)

1.4142135623730951

In [43]:
np.corrcoef(b)

1.0

## Concepts of Broadcasting

In [44]:
# Addition
c = np.array([[1,2,3],[4,5,6]])
d = np.array([3,4,5])
print(c)
print(d)
print(np.sum([c,d])) # Addition only has the square brackets to perform the addition operations.

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[ 4  6  8]
 [ 7  9 11]]


In [45]:
# Subtraction
c = np.array([[1,2,3],[4,5,6]])
d = np.array([3,4,5])
print(c)
print(d)
print(np.subtract(c,d))

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[-2 -2 -2]
 [ 1  1  1]]


## Numpy Indexing and Sclicing

In [46]:
st = np.array(["H","e","l","l","o" ,"w","o","r","l","d","!"])
print(st[-11:-1])

['H' 'e' 'l' 'l' 'o' 'w' 'o' 'r' 'l' 'd']


In [47]:
j = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(j)
print(j[0]) # Print the first row of the array
print(j[:1]) # Printthe first row of the array coz [:1] is print the value excluding the 1 indexing. 
print(j[:2]) # Same as the excluding 2 indexing it's mean 1st and 2nd rows of the array.
print(j[:,1:]) # Excluding the first column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[1 2 3]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


In [48]:
print(j[:,:2])

[[1 2]
 [4 5]
 [7 8]]


In [49]:
print(j[:2,2:])

[[3]
 [6]]


## Array Manipulation 

In [50]:
# Array Concatination
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.concatenate([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([[11,12,13,14,15],[16,17,18,19,20]])
np.concatenate([a,b])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Stack Arrays row_wise and column-wise

In [52]:
print(np.stack([a,b],axis=0))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [53]:
print(np.stack([a,b],axis=1))

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [16 17 18 19 20]]]


In [54]:
# Horizontal Method
np.hstack([a,b])

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [55]:
# Vertical Method
np.vstack([a,b])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Combining column wise stacked array

In [56]:
np.column_stack((a,b))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

## Spliting arrays

In [57]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [77]:
print(np.split(a,2,0))
print(np.split(a,2,axis=0))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]
[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]


In [78]:
print(np.split(a,[1,2],axis=0))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([], shape=(0, 5), dtype=int32)]


In [81]:
a[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [83]:
a[:0]

array([], shape=(0, 5), dtype=int32)

In [84]:
a[:1]

array([[1, 2, 3, 4, 5]])

In [85]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [94]:
a[:,:1]

array([[1],
       [6]])

In [95]:
a[:,1:2]

array([[2],
       [7]])

In [96]:
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [100]:
a[:,-1:]

array([[ 5],
       [10]])

## List vs Numpy 

In [101]:
# Memory size of each that

In [102]:
import numpy as np
import sys

In [103]:
# Define a list
a = range(1000)
print(a)
print("Size of the list:",sys.getsizeof(a)*len(a))

# Define a Numpy
a = np.arange(1000)
print("Size of an array:",a.size*a.itemsize)


range(0, 1000)
Size of the list: 48000
Size of an array: 4000
